# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f6d563c8fe190cdb853bbd750ef46d36597f07b6641b7bee80f660e975620d9b9260d3bce1eaafa37aeeea2f804f375ff56179956374ed791838da1f16c437f

test:
  secret_key_base: 75316f615a4be3b356bff01ac01382c4fe66fac889dbea4e3ca8bd450a911c4557471e1cf4229003454a36ddb26a6529e729a72d82de39f64931362ac72da40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
